name: CD - Deploy Docker Image

on:
  push:
    branches:
      - main  # Run CD on push to the main branch

jobs:
  cd-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-angular-app .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-angular-app my-docker-repo/my-angular-app:latest
          docker push my-docker-repo/my-angular-app:latest

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no centos@52.59.222.15 << 'EOF'
            docker pull my-docker-repo/my-angular-app:latest
            docker stop my-angular-app || true
            docker rm my-angular-app || true
            docker run -d --name my-angular-app -p 80:80 my-docker-repo/my-angular-app:latest
          EOF
