name: CI - Build and Test

on:
  pull_request:
    branches:
      - master  # Run CI on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: payoneer

      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: payoneer

      - name: Build Angular app
        run: ng build --prod
        working-directory: payoneer

      - name: Run unit tests
        run: ng test --watch=false --browsers=ChromeHeadless
        working-directory: payoneer

      - name: Run end-to-end tests
        run: ng e2e --protractor-config=e2e/protractor.conf.js
        working-directory: payoneer
